from pymilvus import Collection

def get_top_n_chunks(collection_name, search_vector, expr, output_fields, limit):
    search_params = {
        "metric_type": "L2", 
        "offset": 0, 
        "ignore_growing": False, 
        "params": {"nprobe": 10}
    }

    collection = Collection(collection_name)
    # find the top most relevant chunks based on the search vector generated by the user's question
    results = collection.search(
        data=[search_vector], 
        anns_field="embedding",
        param=search_params,
        expr=expr,
        limit=limit,
        output_fields=output_fields
    )

    return results[0]

